name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run tests Controller
        run: npm run test-controller
      - name: Start API Rest
        run: npm start &

      - name: Start API GraphQL
        run: npm run star-graphql

      - name: Esperar a API estar funcionando
        run: sleep 5
      - name: Run tests External
        run: npm run test-external 
        